service: react-portfolio

provider:
  name: aws
  region: ap-northeast-1
  runtime: nodejs12.x
  memorySize: 512
  timeout: 30

plugins:
  - serverless-webpack

functions:
  sitePower:
    handler: src/handler.handler
